{
  "openapi": "3.0.0",
  "info": {
    "title": "users",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://dev.dhakon/api/v1",
      "description": "Development"
    },
    {
      "url": "https://staging.dhakon/api/v1",
      "description": "Staging"
    },
    {
      "url": "https://dhakon/api/v1",
      "description": "Production"
    }
  ],
  "paths": {
    "/users/{userId}": {
      "parameters": [
        {
          "schema": {
            "type": "integer"
          },
          "name": "userId",
          "in": "path",
          "required": true,
          "description": "Id of an existing user."
        }
      ],
      "get": {
        "summary": "Get User Info by User ID",
        "tags": [],
        "responses": {
          "200": {
            "description": "User Found",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "../Models/res_success.v1.json"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "./users.v1.json"
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 200,
                      "success": true,
                      "message": "Get profile data successfully",
                      "data": {
                        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                        "first_name": "Muhammad",
                        "last_name": "Najib",
                        "email": "najib@gmail.com",
                        "phone_number": "+6281234567890",
                        "avatar": "http://example.com",
                        "gender": null,
                        "role": "DEMANDER",
                        "password": "pa$$word",
                        "confirm_password": "pa$$word",
                        "status": "ACTIVE",
                        "email_verified": true,
                        "phone_verified": true,
                        "password_change_log": [
                          {
                            "currently": true,
                            "password": "pa$$word",
                            "previous password": "pa$$word",
                            "location": "string",
                            "changed_at": "2019-08-24T14:15:22Z"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error_unauthorized.v1.json"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 401,
                      "success": false,
                      "message": "The client passed in the invalid Auth token. Client should refresh the token and then try again."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error.v1.json"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 404,
                      "success": false,
                      "message": "User Not Found"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-users-userId",
        "description": "Retrieve the information of the user with the matching user ID.",
        "security": [
          {
            "Token": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "example": "application/json",
              "default": "application/json"
            },
            "in": "header",
            "name": "Content-Type",
            "required": true
          }
        ]
      },
      "patch": {
        "summary": "Update User Information",
        "operationId": "patch-users-userId",
        "responses": {
          "200": {
            "description": "User Updated",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "../Models/res_success.v1.json"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "./users-partial.v1.json"
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 200,
                      "success": true,
                      "message": "Get data successfully",
                      "data": {
                        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                        "first_name": "Muhammad",
                        "last_name": "Najib",
                        "email": "najib@gmail.com",
                        "phone_number": "+6281234567890",
                        "avatar": "http://example.com",
                        "gender": null,
                        "role": "DEMANDER",
                        "status": "ACTIVE",
                        "email_verified": true,
                        "phone_verified": true
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error_unauthorized.v1.json"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 401,
                      "success": false,
                      "message": "The client passed in the invalid Auth token. Client should refresh the token and then try again."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error.v1.json"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 404,
                      "success": false,
                      "message": "User Not Found"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Email Already Taken",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error.v1.json"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 409,
                      "success": true,
                      "message": "Conflict",
                      "errors": [
                        {
                          "message": "Email Already Taken",
                          "code": 29,
                          "field": "Email"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Update the infromation of an existing user.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "first_name": {
                    "type": "string",
                    "example": "Muhammad"
                  },
                  "last_name": {
                    "type": "string",
                    "example": "Najib"
                  },
                  "email": {
                    "type": "string",
                    "format": "email",
                    "example": "imelenajib@gmail.com"
                  },
                  "phone_number": {
                    "type": "string",
                    "example": "081234567890"
                  },
                  "avatar": {
                    "type": "string",
                    "format": "uri"
                  }
                }
              },
              "examples": {
                "Change Fully": {
                  "value": {
                    "first_name": "Muhammad",
                    "last_name": "Najib",
                    "email": "imelenajib@gmail.com",
                    "phone_number": "081234567890",
                    "avatar": "http://example.com"
                  }
                },
                "Change Name Only": {
                  "value": {
                    "first_name": "Muhammad",
                    "last_name": "Najib"
                  }
                },
                "Change Email Only": {
                  "value": {
                    "email": "imelenajib@gmail.com"
                  }
                },
                "Change Phone Only": {
                  "value": {
                    "phone_number": "081234567890"
                  }
                },
                "Change Avatar": {
                  "value": {
                    "avatar": "http://example.com"
                  }
                }
              }
            }
          },
          "description": "Patch user properties to update."
        },
        "security": [
          {
            "Token": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "example": "application/json",
              "default": "application/json"
            },
            "in": "header",
            "name": "Content-Type",
            "required": true
          }
        ]
      }
    },
    "/users": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "../Models/res_success.v1.json"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "array",
                          "items": {
                            "$ref": "./users-partial.v1.json"
                          }
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 200,
                      "success": true,
                      "message": "Get users data successfully",
                      "data": [
                        {
                          "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                          "first_name": "Muhammad",
                          "last_name": "Najib",
                          "email": "najib@gmail.com",
                          "phone_number": "+6281234567890",
                          "avatar": "http://example.com",
                          "gender": null,
                          "role": "DEMANDER",
                          "status": "ACTIVE",
                          "email_verified": true,
                          "phone_verified": true
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error_unauthorized.v1.json"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 401,
                      "success": false,
                      "message": "The client passed in the invalid Auth token. Client should refresh the token and then try again."
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-users",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "uuid",
              "default": "497f6eca-6276-4993-bfeb-53cbbbba6f08"
            },
            "in": "query",
            "name": "profiles",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Content-Type",
            "required": true
          }
        ],
        "security": [
          {
            "Token": []
          }
        ]
      }
    },
    "/users/{userId}/change-role": {
      "patch": {
        "summary": "",
        "operationId": "patch-users-change-role",
        "responses": {
          "200": {
            "description": "Role User Updated",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "../Models/res_success.v1.json"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "./users-partial.v1.json"
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 200,
                      "success": true,
                      "message": "Update role user successfully",
                      "data": {
                        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                        "first_name": "Muhammad",
                        "last_name": "Najib",
                        "email": "najib@gmail.com",
                        "phone_number": "+6281234567890",
                        "avatar": "http://example.com",
                        "gender": null,
                        "role": "DEMANDER",
                        "status": "ACTIVE",
                        "email_verified": true,
                        "phone_verified": true
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error_unauthorized.v1.json"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 401,
                      "success": false,
                      "message": "The client passed in the invalid Auth token. Client should refresh the token and then try again."
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "Token": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Content-Type",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "",
                "type": "object",
                "properties": {
                  "role": {
                    "type": [
                      "string",
                      "null"
                    ],
                    "minLength": 1,
                    "default": "DEMANDER"
                  }
                },
                "required": [
                  "role"
                ]
              }
            }
          }
        },
        "description": ""
      },
      "parameters": []
    },
    "/users/{userId}/demands": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "../Models/res_success.v1.json"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "array",
                          "items": {
                            "$ref": "../Demands/demand-partial.v1.json"
                          }
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 200,
                      "success": true,
                      "message": "Get demand data successfully",
                      "data": [
                        {
                          "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                          "title": "Saya butuh bawang merah",
                          "category_item_id": "46fa068d-c0a7-40ac-ad84-951892b10de9",
                          "item": {
                            "name": "Bawang Merah",
                            "qty": "10",
                            "unit": "Kwintal"
                          },
                          "city_id": "4e4d55fa-e3bf-4bdb-9825-519278b117b5",
                          "description": "Tawarkan bawang merah terbaik kamu",
                          "deadline": "2019-08-24",
                          "status": "OPEN"
                        },
                        {
                          "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                          "title": "Saya butuh bawang merah",
                          "category_item_id": "46fa068d-c0a7-40ac-ad84-951892b10de9",
                          "item": {
                            "name": "Bawang Merah",
                            "qty": "10",
                            "unit": "Kwintal"
                          },
                          "city_id": "4e4d55fa-e3bf-4bdb-9825-519278b117b5",
                          "description": "Tawarkan bawang merah terbaik kamu",
                          "deadline": "2019-08-24",
                          "status": "OPEN"
                        },
                        {
                          "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                          "title": "Saya butuh bawang merah",
                          "category_item_id": "46fa068d-c0a7-40ac-ad84-951892b10de9",
                          "item": {
                            "name": "Bawang Merah",
                            "qty": "10",
                            "unit": "Kwintal"
                          },
                          "city_id": "4e4d55fa-e3bf-4bdb-9825-519278b117b5",
                          "description": "Tawarkan bawang merah terbaik kamu",
                          "deadline": "2019-08-24",
                          "status": "OPEN"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error_unauthorized.v1.json"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 401,
                      "success": true,
                      "message": "The client passed in the invalid Auth token. Client should refresh the token and then try again."
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-users-demands",
        "security": [
          {
            "Token": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Content-Type",
            "required": true
          }
        ]
      },
      "parameters": [],
      "post": {
        "summary": "",
        "operationId": "post-users-userId-demands",
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "../Models/res_success.v1.json"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "../Demands/demand-partial.v1.json"
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 201,
                      "success": true,
                      "message": "Create new demand successfully",
                      "data": {
                        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                        "title": "Saya butuh bawang merah",
                        "category_item_id": "46fa068d-c0a7-40ac-ad84-951892b10de9",
                        "item": {
                          "name": "Bawang Merah",
                          "qty": "10",
                          "unit": "Kwintal"
                        },
                        "city_id": "4e4d55fa-e3bf-4bdb-9825-519278b117b5",
                        "description": "Tawarkan bawang merah terbaik kamu",
                        "deadline": "2019-08-24",
                        "status": "OPEN"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error.v1.json"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 400,
                      "success": false,
                      "message": "Your request parameters didn't validate.",
                      "errors": [
                        {
                          "message": "Field 'description' is required",
                          "code": 12,
                          "field": "description"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error_unauthorized.v1.json"
                }
              }
            }
          }
        },
        "security": [
          {
            "Token": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Content-Type",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "",
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "minLength": 1
                  },
                  "category_item_id": {
                    "type": "string",
                    "minLength": 1
                  },
                  "item": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string",
                        "minLength": 1
                      },
                      "qty": {
                        "type": "string",
                        "minLength": 1
                      },
                      "unit": {
                        "type": "string",
                        "minLength": 1
                      }
                    },
                    "required": [
                      "name",
                      "qty",
                      "unit"
                    ]
                  },
                  "city_id": {
                    "type": "string",
                    "minLength": 1
                  },
                  "description": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "title",
                  "category_item_id",
                  "item",
                  "city_id",
                  "description"
                ]
              },
              "examples": {
                "Example": {
                  "value": {
                    "title": "Saya butuh bawang merah",
                    "category_item_id": "46fa068d-c0a7-40ac-ad84-951892b10de9",
                    "item": {
                      "name": "Bawang Merah",
                      "qty": "10",
                      "unit": "Kwintal"
                    },
                    "city_id": "4e4d55fa-e3bf-4bdb-9825-519278b117b5",
                    "description": "Tawarkan bawang merah terbaik kamu"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "",
        "operationId": "put-users-userId-demands",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "../Models/res_success.v1.json"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "../Demands/demand-partial.v1.json"
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 200,
                      "success": true,
                      "message": "Update demand data successfully",
                      "data": {
                        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                        "title": "Saya butuh bawang merah",
                        "category_item_id": "46fa068d-c0a7-40ac-ad84-951892b10de9",
                        "item": {
                          "name": "Bawang Merah",
                          "qty": "10",
                          "unit": "Kwintal"
                        },
                        "city_id": "4e4d55fa-e3bf-4bdb-9825-519278b117b5",
                        "description": "Tawarkan bawang merah terbaik kamu",
                        "deadline": "2019-08-24",
                        "status": "OPEN"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error.v1.json"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 400,
                      "success": false,
                      "message": "Your request parameters didn't validate.",
                      "errors": [
                        {
                          "message": "Field 'description' is required",
                          "code": 12,
                          "field": "description"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error_unauthorized.v1.json"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "code": 401,
                      "success": true,
                      "message": "The client passed in the invalid Auth token. Client should refresh the token and then try again."
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "Token": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/jso"
            },
            "in": "header",
            "name": "Content-Type",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "",
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "minLength": 1
                  },
                  "category_item_id": {
                    "type": "string",
                    "minLength": 1
                  },
                  "item": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string",
                        "minLength": 1
                      },
                      "qty": {
                        "type": "string",
                        "minLength": 1
                      },
                      "unit": {
                        "type": "string",
                        "minLength": 1
                      }
                    },
                    "required": [
                      "name",
                      "qty",
                      "unit"
                    ]
                  },
                  "city_id": {
                    "type": "string",
                    "minLength": 1
                  },
                  "description": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "title",
                  "category_item_id",
                  "item",
                  "city_id",
                  "description"
                ]
              },
              "examples": {
                "Example": {
                  "value": {
                    "title": "Saya butuh bawang merah",
                    "category_item_id": "46fa068d-c0a7-40ac-ad84-951892b10de9",
                    "item": {
                      "name": "Bawang Merah",
                      "qty": "10",
                      "unit": "Kwintal"
                    },
                    "city_id": "4e4d55fa-e3bf-4bdb-9825-519278b117b5",
                    "description": "Tawarkan bawang merah terbaik kamu"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "",
        "operationId": "delete-users-userId-demands",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_success.v1.json"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 200,
                      "success": true,
                      "message": "Remove all demand data successfully"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../Models/res_error_unauthorized.v1.json"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "code": 401,
                      "success": true,
                      "message": "The client passed in the invalid Auth token. Client should refresh the token and then try again."
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "Token": []
          }
        ],
        "parameters": []
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {
      "Token": {
        "type": "http",
        "scheme": "bearer",
        "description": ""
      }
    }
  }
}